[project]
name = "mcp-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.2.10",
    "google-genai>=1.9.0",
    "mcp>=1.6.0",
]
