[project]
name = "rag-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "openai>=1.102.0",
]
