services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: postgress-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
