[project]
name = "agents-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai-tools>=0.32.1",
    "crewai>=0.98.0",
]
